# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/2i2c-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
    nodejs: "16"
  jobs:
    post_checkout:
      # Make sure last-updated commits are available
      - git fetch --unshallow || true

sphinx:
  configuration: conf.py
  builder: dirhtml

python:
  install:
    - requirements: requirements.txt
