name: Build documentation and check links

on:
  workflow_dispatch:
  schedule:
  # Runs at 1am each day.
  - cron: '0 1 * * *'

jobs:
  linkcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install mystmd
        run: pip install mystmd

      - name: Build the site and check links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: myst build --html --check-links --strict
