name: Auto-update onboarding/offboarding issues with accounts list
on:
  issues:
    types: [opened, labeled]

jobs:
  update-issue:
    runs-on: ubuntu-latest

    if: |
      contains(github.event.issue.labels.*.name, 'type: onboard') ||
      contains(github.event.issue.labels.*.name, 'type: offboard')

    steps:
      - uses: actions/checkout@v4

      - name: Read accounts.md
        run: |
          {
            echo 'accounts<<EOF'
            cat .github/workflows/accounts.md
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Add comment with accounts list
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.read_accounts.outputs.accounts }}
