name: Auto-update onboarding/offboarding issues with accounts list
on:
  issues:
    types: [opened, labeled]

jobs:
  update-issue:
    runs-on: ubuntu-latest

    if: |
      contains(github.event.issue.labels.*.name, 'type: onboard') ||
      contains(github.event.issue.labels.*.name, 'type: offboard')

    steps:
      - uses: actions/checkout@v4

      - name: Read accounts.md
        id: read_accounts
        run: |
          {
            printf 'accounts<<EOF\n'
            cat .github/workflows/accounts.md
            printf '\nEOF\n'
          } >> "$GITHUB_OUTPUT"

      - name: Append Issue Body
        uses: julien-deramond/update-issue-body@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Cloud engineering permissions**

            ${{ steps.read_accounts.outputs.accounts }}
          edit-mode: append
